title: Dena Wilson
<a href="url"><img src="https://github.com/user-attachments/assets/597e2b9a-c2b0-4894-a409-c691becd33d8" align="left" height="108" width="108" ></a>

#Projects involving SQL, Python, Power BI, Tableau and more.
#show_downloads: true
theme: jekyll-theme-minimal
